import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {
  Col,
  Row,
} from 'react-bootstrap';

import BlockContainer from './components/BlockContainer';
import Footer from './layout/Footer/Footer';
import SiteHeader from './layout/header/Header';
import SideNav from './layout/SideNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='he' dir='rtl'>
      <body className={inter.className}>
      <SiteHeader/>
        <BlockContainer>
          <Row className='m-0 p-0'>
            <Col
              md={2}
              className='sticky shadow border-t border-white border-l m-0 p-0 h-[100vh] bg-gray-800'
              style={{ position: 'sticky', top: 0 }}>
              <SideNav />
            </Col>
            <Col md={10} className='m-0 p-0 h-[100vh]'>
              {children}
            </Col>
          </Row>
        </BlockContainer>
        <Footer/>
      </body>
    </html>
  );
}

